[app]

title = Mesaj Uygulamam

package.name = mesajuygulamam

package.domain = org.mesajuygulamam

source.dir = .

source.include_exts = py,json,png,jpg,jpeg,kv,atlas

version = 1.0

requirements = python3,kivy==2.3.1,websockets

orientation = portrait

fullscreen = 0

android.permissions = INTERNET

android.api = 36

android.ndk = 29

android.accept_sdk_license = True

android.minapi = 24

android.archs = arm64-v8a, armeabi-v7a

android.allow_backup = True


[buildozer]

log_level = 2

warn_on_root = 1
